name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.0.15
  # get it singleton
  get_it: ^7.6.0
  # equatable
  equatable: ^2.0.5
  # bloc state manager
  flutter_bloc: ^8.1.3
  # async
  async: ^2.11.0
  # forms
  formz: ^0.6.0
  # internet check
  connectivity_plus: ^4.0.1
  internet_connection_checker_plus: ^2.0.0
  # freezed
  freezed_annotation: ^2.4.1
  # interceptor
  dio: ^5.3.0
  dio_retry_plus: ^2.0.0
  # alice = chuck
  chuck_interceptor: ^2.0.1
  # box
  gap: ^3.0.1
  # pin put:
  pinput: ^2.2.31
  # svg render
  flutter_svg: ^2.0.7
  # cached image
  cached_network_image: ^3.2.3
  # native splash
  flutter_native_splash: ^2.3.1
  # firebase
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  # local notification
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.3
  freezed: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/
    - assets/png/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
