name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # hive no sql database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # internet check
  connectivity_plus: ^2.3.9
  # keyboard dismiss
  keyboard_dismisser: ^3.0.0
  # freezed
  freezed_annotation: any
  # get it singleton
  get_it: ^7.2.0
  # bloc state manager
  flutter_bloc: ^8.1.1
  # rest api
  http: ^0.13.5
  # interceptor
  dio: ^4.0.6
  dio_retry_plus: ^1.0.2
  # retrofit
  retrofit: any
  # alice = chuck
  chuck_interceptor: ^1.0.7
  # translator
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  retrofit_generator: any
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.0
  freezed: any
  http_mock_adapter: ^0.3.3
  mockito: ^5.3.2

flutter:
  generate: true

  uses-material-design: true

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf