name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.1.0
  lottie: ^3.0.0
  image_picker: ^1.0.5
  fluttertoast: ^8.0.7
  url_launcher: ^6.2.2
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  badges: ^2.0.1
  sqflite: ^2.3.0
  path: ^1.8.0
  floor: ^1.4.2
  provider: ^6.1.1
  shared_preferences: ^2.0.9
  # hive no sql database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # path
  path_provider: ^2.0.15
  # get it singleton
  get_it: ^7.6.0
  # equatable
  equatable: ^2.0.5
  # bloc state manager
  flutter_bloc: ^8.1.3
  # async
  async: ^2.11.0
  # forms
  formz: ^0.6.0
  # internet check
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  # interceptor
  dio: ^5.3.2
  dio_retry_plus: ^2.0.0
  # alice = chuck
  chuck_interceptor: ^2.0.1
  # box
  gap: ^3.0.1
  # pin put:
  pinput: ^3.0.0
  # svg render
  flutter_svg: ^2.0.7
  # dropdown
  dropdown_button2: ^2.3.7
  # cached image
  cached_network_image: ^3.2.3
  # native splash
  flutter_native_splash: ^2.3.1
  # share
  share_plus: ^7.2.1
  # local notification
  flutter_local_notifications: ^15.1.0+1
  retrofit: '>=4.0.0 <5.0.0'
  get: ^4.5.0
  carousel_slider: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/
    - assets/png/asia.png
    - assets/png/search.png
    - assets/png/bag.png
    - assets/png/user.png
    - assets/png/asia_noText.png
    - assets/png/empty_cart.jpg
    - assets/png/profilimage.png
    - assets/png/asia_banner.png
    - assets/png/phone.png
    - assets/png/telegram.png

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf



flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/png/asia_noText.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
