name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # hive no sql database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # internet check
  connectivity_plus: ^4.0.0
  # keyboard dismiss
  keyboard_dismisser: ^3.0.0
  # freezed
  freezed_annotation: ^2.2.0
  # get it singleton
  get_it: ^7.6.0
  # bloc state manager
  flutter_bloc: ^8.1.2
  # interceptor
  dio: ^5.1.2
  dio_retry_plus: ^1.0.3
  # retrofit
  retrofit: ^4.0.1
  # alice = chuck
  chuck_interceptor: ^1.1.4
  # translator
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0+3
  http_mock_adapter: ^0.4.4
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  bloc_test: ^9.1.1
  freezed: ^2.3.3
  mockito: ^5.4.0

flutter:
  generate: true

  uses-material-design: true

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf