name: sample_bloc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

analyzer:
  enable-experiment:
    - non-nullable
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.0.15
  # equatable
  equatable: ^2.0.5
  # forms
  formz: ^0.6.0
  dartz: ^0.10.1
  # internet check
  connectivity_plus: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  # keyboard dismiss
  keyboard_dismisser: ^3.0.0
  # cached image
  cached_network_image: ^3.2.3
  # freezed
  freezed_annotation: ^2.2.0
  # get it singleton
  get_it: ^7.6.0
  # bloc state manager
  flutter_bloc: ^8.1.2
  # interceptor
  dio: ^5.1.2
  dio_retry_plus: ^1.0.3
  # retrofit
  retrofit: ^4.0.1
  # alice = chuck
#  chuck_interceptor: ^1.1.4
  # box
  gap: ^3.0.0
  # repository generator
  analyzer: ^5.12.0
#  repo_annotation: ^0.0.1
  # native splash
  flutter_native_splash: ^2.2.19
  # pinput:
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0+3
  hive_generator: ^2.0.0
#  repo_generator:
#    git:
#      url: https://github.com/SunnatilloShavkatov/repo_generator.git
#      ref: main
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  bloc_test: ^9.1.1
  freezed: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
