List<Map<String, dynamic>> slugs=[

    {'name': "O'lchash srtakanlari", 'slug': 'olchash-srtakanlari'},
    {'name': 'Oziq-ovqat idishlari', 'slug': 'oziq-ovqat-idishlari'},
    {'name': 'Vazalar vqa shamdonlar', 'slug': 'vazalar-vqa-shamdonlar'},
    {'name': 'Almarjan', 'slug': 'almarjan'},
    {'name': 'Anisa', 'slug': 'anisa'},
    {'name': 'Arshia', 'slug': 'arshia'},
    {'name': 'AsiaPosuda', 'slug': 'asiaposuda'},
    {'name': 'Autumn', 'slug': 'autumn'},
    {'name': 'Bambuk idishlar', 'slug': 'posuda-iz-bambuka'},
    {'name': 'Bezatish', 'slug': 'dekorirovanie'},
    {'name': 'Kremanka', 'slug': 'kremanka'},
    {'name': 'Menajnitsa', 'slug': 'menazhnicza'},
    {'name': 'Meva va konfet idishlari', 'slug': 'fruktovniczy-i-konfetniczy'},
    {'name': 'Muz idishlari', 'slug': 'emkosti-dlya-lda'},
    {'name': 'Patnislar', 'slug': 'podnosy'},
    {'name': "Saryog' uchun idish", 'slug': 'maslenki'},
    {'name': 'Tort va pishiriqlar uchun', 'slug': 'blyuda-i-tortniczy'},
    {'name': 'Vazalar va shamdonlar', 'slug': 'vazy-i-podsvechniki'},
    {'name': 'Billi', 'slug': 'billi'},
    {'name': 'Bolalar uchun', 'slug': 'dlya-detej'},
    {'name': 'Bolalar kosasi', 'slug': 'detskie-kosushki'},
    {'name': 'Bolalar likopchalari', 'slug': 'detskie-tarelki'},
    {'name': 'Bolalar qoshiq va sanchqilari', 'slug': 'detskie-lozhki-i-vilki'},
    {'name': 'Bolalar tushlik qutilari', 'slug': 'detskie-lanch-boksy'},
    {'name': "Bolalar uchun idishlar to'plami", 'slug': 'detskij-nabor-posudy'},
    {'name': 'Bolalar uchun suv idishlari', 'slug': 'butylki-dlya-detej'},
    {'name': 'Brabantia', 'slug': 'brabantia'},
    {'name': 'Brioni', 'slug': 'brioni'},
    {'name': 'Bueno', 'slug': 'bueno'},
    {'name': 'Corona', 'slug': 'corona'},
    {'name': 'Corona Посуда', 'slug': 'corona-posuda'},
    {'name': 'Dinova Saina', 'slug': 'dinova-saina'},
    {'name': 'Domassi', 'slug': 'domassi'},
    {'name': "Endlo's", 'slug': 'endlos'},
    {'name': 'Evren', 'slug': 'evren'},
    {'name': 'Fissman', 'slug': 'fissman'},
    {'name': 'Grand', 'slug': 'grand'},
    {'name': 'Grande', 'slug': 'grande'},
    {'name': 'Homezaza', 'slug': 'homezaza'},
    {'name': 'Ichimliklar uchun', 'slug': 'dlya-napitkov'},
    {'name': 'Baland bokallar', 'slug': 'bokaly-vysokie'},
    {'name': 'Baland stakanlar', 'slug': 'stakany-vysokie'},
    {'name': 'Chovgumlar', 'slug': 'chajniki'},
    {'name': "Choy to'plamlari", 'slug': 'chajnye-nabory'},
    {'name': 'Choynaklar', 'slug': 'chajniki-zavarochnye'},
    {'name': 'Grafinlar', 'slug': 'grafiny'},
    {'name': 'Kompot idishlari', 'slug': 'kompotniczy'},
    {'name': 'Krujkalar', 'slug': 'kruzhki'},
    {'name': 'Martinkalar', 'slug': 'martinki'},
    {'name': 'Past bokallar', 'slug': 'bokaly-nizkie'},
    {'name': 'Past stakanlar', 'slug': 'stakany-nizkie'},
    {'name': "Salqin ichimliklar uchun to'plamlar", 'slug': 'nabory-dlya-holodnyh-napitkov'},
  {'name': "Idishlar to'plami", 'slug': 'nabory-posuda'},
  {'name': 'Lamart', 'slug': 'lamart'},
  {'name': 'Life Smile', 'slug': 'life-smile'},
  {'name': 'luminarc', 'slug': 'luminarc-2'},
  {'name': 'Magic', 'slug': 'magic'},
  {'name': 'Maishiy texnika', 'slug': 'bytovaya-tehnika'},
  {'name': 'Blenderlar', 'slug': 'blendery'},
  {'name': 'Changyutgichlar', 'slug': 'pylelosy'},
  {'name': 'Dazmol', 'slug': 'utyug'},
  {'name': 'Elektron choynaklar', 'slug': 'tefali'},
  {'name': "Elektron go'sht maydalagichlar", 'slug': 'elektronnye-myasorubki'},
  {'name': 'Elektron vafli pishirgichlar', 'slug': 'elektron-vafli-pishirgichlar'},
  {'name': 'Kofe maydalagichlar', 'slug': 'kofemolki'},
  {'name': 'Kofe tayyorlagichlar', 'slug': 'kofevarki'},
  {'name': 'Maydalagichlar', 'slug': 'choppery'},
  {'name': 'Mikserlar', 'slug': 'miksery'},
  {'name': 'Multivarkalar', 'slug': 'multivarki'},
  {'name': 'Soch uchun fenlar', 'slug': 'fen-dlya-volos'},
  {'name': 'Suv nasoslari', 'slug': 'pompa'},
  {'name': 'Tarozilar', 'slug': 'vesy'},
  {'name': 'Tosterlar', 'slug': 'tostery'},
  {'name': "Uy uchun texnikalar to'plami", 'slug': 'nabor-tehniki-dlya-doma'},
  {'name': 'MEGA', 'slug': 'mega'},
  {'name': 'Millenium', 'slug': 'millenium'},
  {'name': 'Neman', 'slug': 'neman'},
  {'name': 'Oq farfor idishlar', 'slug': 'belaya-farforovaya-posuda'},
  {'name': 'Oq melamin idishlar', 'slug': 'belaya-melaminovaya-posuda'},
  {'name': 'Oshxona anjomlari', 'slug': 'kuhonnye-instrumenty'},
  {'name': "Bolg'alar", 'slug': 'molotki'},
  {'name': "Cho'mich-kapgirlar", 'slug': 'povareshki-kuhonnye-instrumenty'},
  {'name': "Cho'tkalar", 'slug': 'kistochki'},
  {'name': 'Elak', 'slug': 'sito'},
  {'name': 'Elita vositalari', 'slug': 'elitnye-instrumenty'},
  {'name': 'Idish quritgichlar', 'slug': 'sushilki-dlya-posudy'},
  {'name': "Ko'pirtirgich", 'slug': 'venchiki-kuhonnye-instrumenty'},
  {'name': 'Lopatalar', 'slug': 'lopatki'},
  {'name': 'Mastxev asboblar', 'slug': 'masthevy-instrumenty'},
  {'name': 'Maydalagichlar', 'slug': 'melniczy'},
  {'name': "O'lchash stakanlari", 'slug': 'mernye-stakany'},
  {'name': "O'qlov", 'slug': 'skalki'},
  {'name': 'Ochqichlar', 'slug': 'otkryvalki'},
  {'name': 'Pishirish vositalari', 'slug': 'kulinarnye-instrumenty'},
  {'name': "Qirg'ichlar", 'slug': 'terki-kuhonnye-instrumenty'},
  {'name': 'Qiskichlar', 'slug': 'shhipczy'},
  {'name': 'Qoshiq va sanchqilar uchun idish', 'slug': 'podstavki-dlya-lozhek-i-vilok'},
  {'name': 'Sabzavot tozalagichlar', 'slug': 'ovoshhechistki'},
  {'name': 'Sarimsoq piyoz maydalagich', 'slug': 'pressy-dlya-chesnoka'},
  {'name': 'Silikon supralar', 'slug': 'silikonovye-kovriki'},
  {'name': 'Sochiqlar', 'slug': 'polotencza'},
  {'name': 'Suzgichlar', 'slug': 'durshlagi'},
  {'name': 'Tutqichlar', 'slug': 'prihvatki'},
  {'name': 'Sharbat chiqargichlar', 'slug': 'sokovyzhimalki'},
  {'name': 'Parem', 'slug': 'parem'},
  {'name': 'Perilla', 'slug': 'perilla'},
  {'name': 'Pishirish', 'slug': 'prigotovlenie'},
  {'name': "Cho'yan idishlar", 'slug': 'chugunnaya-posuda'},
  {'name': 'Issiqqa chdamli idishlar', 'slug': 'posuda-zharoprochnaya'},
  {'name': 'Kastryulkalar', 'slug': 'kastryuli'},
  {'name': 'Mantiqasqonlar', 'slug': 'mantovarki'},
  {'name': 'Maxsus pichoqlar', 'slug': 'speczialnye-nozhi'},
  {'name': "O'choq va uchoyoqlar", 'slug': 'uchagi-i-trenogi'},
  {'name': 'Oshxona pichoqlari', 'slug': 'kuhonnye-nozhi'},
  {'name': "Pichoq o'tkirlagich", 'slug': 'nozhetochki'},
  {'name': 'Pichoq stendlari', 'slug': 'podstavki-dlya-nozhej'},
  {'name': "Pichoq to'plamlari", 'slug': 'nabory-nozhej'},
  {'name': "Qo'ra va tutunxonalar", 'slug': 'mangaly-i-koptilni'},
  {'name': 'Qopqoqlar', 'slug': 'kryshki'},
  {'name': 'Qovurma qozon', 'slug': 'zharovni'},
  {'name': 'Tovalar', 'slug': 'skovorodki'},
  {'name': 'Qozonlar', 'slug': 'kazany'},
  {'name': 'Turkalar', 'slug': 'turki'},
  {'name': 'Tutqichli kastryul', 'slug': 'sotejnik'},
  {'name': 'Taxtakashlar', 'slug': 'razdelochnye-doski-2'},
  {'name': 'Barbekyu va sixlar', 'slug': 'reshetki-i-shampury'},
  {'name': 'Pishirish uchun shakllar', 'slug': 'formy-dlya-vypechki-posuda-dlya-zapekaniya-2'},
  {'name': 'Promsiz', 'slug': 'promsiz'},
  {'name': 'Qora melamin idishlar', 'slug': 'chernaya-melaminovaya-posuda'},
  {'name': 'Qoshiq-sanchqilar', 'slug': 'stolovye-pribory'},
  {'name': "Qoshiq va sanchqi to'plamlari", 'slug': 'nabory-stolovyh-priborov'},
  {'name': 'Qoshiqlar', 'slug': 'lozhki'},
  {'name': 'Sanchqilar', 'slug': 'vilki'},
  {'name': 'Queen', 'slug': 'queen'},
  {'name': 'Rich', 'slug': 'rich'},
  {'name': 'Saqlash', 'slug': 'hranenie'},
  {'name': 'Banka va konteynerlar', 'slug': 'banki-i-emkosti'},
  {'name': 'Sabzavot idishlari', 'slug': 'banki-dlya-ovoshhej'},
  {'name': 'Temir tovoqlar', 'slug': 'miski'},
  {'name': 'Oziq-ovqat konteynerlari', 'slug': 'pishhevye-kontejnery'},
  {'name': 'Non qutilari', 'slug': 'hlebniczy'},
  {'name': 'Servirovka', 'slug': 'servirovka'},
  {'name': 'Kosalar', 'slug': 'kosushki'},
  {'name': 'Likopchalar', 'slug': 'tarelki'},
  {'name': 'Piyolalar', 'slug': 'pialy'},
  {'name': 'Qayla idishlari', 'slug': 'sousniczy'},
  {'name': 'Salat idishlari', 'slug': 'salatniki'},
  {'name': 'Salfetka uchun idishlar', 'slug': 'salfetniczy'},
  {'name': 'Shakar uchun idishlar', 'slug': 'saharniczy'},
  {'name': "Sho'rva idishlari", 'slug': 'supniczy'},
  {'name': 'Tuzdonlar', 'slug': 'solniczy'},
  {'name': 'sonifer', 'slug': 'sonifer'},
  {'name': "Sovg'alar", 'slug': 'podarki'},
  {'name': 'Stoneware', 'slug': 'stoneware'},
  {'name': 'T&amp;J', 'slug': 'tj'},
  {'name': 'Termoslar', 'slug': 'termosy'},
  {'name': 'Ovqat uchun termoslar', 'slug': 'termosy-dlya-edy'},
  {'name': 'Termo-choynaklar', 'slug': 'termochajniki'},
  {'name': 'Termoslar', 'slug': 'termos'},
  {'name': 'Sport butilkalari', 'slug': 'sportivnye-butylki'},
  {'name': 'Muz effektli stakanlar', 'slug': 'stakany-s-effektom-lda'},
  {'name': 'Uy jihozlari', 'slug': 'dom-i-hozyajstvo'},
  {'name': 'Kiyimlar parvarishi uchun', 'slug': 'uhod-za-odezhdoj'},
  {'name': 'Dazmol taxtalari', 'slug': 'gladilnye-doski'},
  {'name': 'Kiyim quritgichlar', 'slug': 'sushilki-dlya-belya'},
  {'name': 'Kiyimlar uchun savatlar', 'slug': 'korziny-dlya-belya'},
  {'name': 'Tozalash', 'slug': 'uborka'},
  {'name': 'Chelaklar', 'slug': 'vedra'},
  {'name': "Hammom uchun to'plamlar", 'slug': 'nabory-dlya-vannoj'},
  {'name': 'Sovun idishlari', 'slug': 'mylniczy'},
  {'name': 'Supurgilar', 'slug': 'veniki-i-sovki'},
  {'name': 'Tozalash uchun lattalar', 'slug': 'tryapki-dlya-uborki'},
  {'name': "Unitaz cho'tkalari", 'slug': 'ershiki'},
  {'name': 'без категории', 'slug': 'bez-kategorii'},
  {'name': 'Бытпласт', 'slug': 'bytplast'},
  {'name': 'Мечта', 'slug': 'mechta'},
  {'name': 'Korkmaz', 'slug': 'korkmaz'},
  {'name': 'Kukmara', 'slug': 'kukmara'},
  {'name': 'Pasabahce', 'slug': 'pasabahce'},
  {'name': 'Torix', 'slug': 'torix'}


];